// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSxe71DPlikV6zOd6hcBlZluAbssdte5w',
    appId: '1:1087747525137:web:79b77e0fb6a97a5f8b7fb0',
    messagingSenderId: '1087747525137',
    projectId: 'footballapp-9a44b',
    authDomain: 'footballapp-9a44b.firebaseapp.com',
    storageBucket: 'footballapp-9a44b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtU1o-y_qKsa_D_M8KnE9FQ0uegxuh9V0',
    appId: '1:1087747525137:android:4da6c5300ef5d75c8b7fb0',
    messagingSenderId: '1087747525137',
    projectId: 'footballapp-9a44b',
    storageBucket: 'footballapp-9a44b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxB-aax0t1F2hSbozZNPMwTrtj65Jphs',
    appId: '1:1087747525137:ios:d5fff19d5502ec6e8b7fb0',
    messagingSenderId: '1087747525137',
    projectId: 'footballapp-9a44b',
    storageBucket: 'footballapp-9a44b.appspot.com',
    iosBundleId: 'com.example.footballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxB-aax0t1F2hSbozZNPMwTrtj65Jphs',
    appId: '1:1087747525137:ios:d5fff19d5502ec6e8b7fb0',
    messagingSenderId: '1087747525137',
    projectId: 'footballapp-9a44b',
    storageBucket: 'footballapp-9a44b.appspot.com',
    iosBundleId: 'com.example.footballApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSxe71DPlikV6zOd6hcBlZluAbssdte5w',
    appId: '1:1087747525137:web:fcaf944b63acc6598b7fb0',
    messagingSenderId: '1087747525137',
    projectId: 'footballapp-9a44b',
    authDomain: 'footballapp-9a44b.firebaseapp.com',
    storageBucket: 'footballapp-9a44b.appspot.com',
  );
}
